### ISSUE TITLE
API for LastAdapter 2.0

### ISSUE THREAD

**Issue by nitrico** [nitrico/LastAdapter#10]
LastAdapter 2.0 is coming soon and I'd like to hear your thoughts or suggestions about its API.

**Listeners**:
* They will be specific for each item type, instead of one for the whole adapter.
* They probably will not provide parameters `view`, `type` and `item` anymore, only **binding** and **position**. `item` and `view` will be available through `binding.item` and `binding.root`.
* I will add an `onRecycle` callback for the view being recycled.
* Maybe another `onCreate` callback for the ViewHolder being created (for the first time). Not sure yet.
* Should I keep the `onClick` and `onLongClick` listeners? Are you really using them? I mean, you can also set them in the layout itself or in the `onBind` callback.

The API for Kotlin is going to be pretty cool, in my opinion:

```kotlin
LastAdapter.with(Data.items, BR.item)
    .map<Header, ItemHeaderBinding>(R.layout.item_header) {
        onCreate { println("Created ${binding.item} at position $position") }
        onBind { println("Bound ${binding.item} at position $position") }
        onClick { context.toast("Click on ${binding.item} at position $position") }
        onLongClick { context.toast("Long click on ${binding.item} at position $position") }
        onRecycle { println("Recycled ${binding.item} at position $position") }
    }
    .map<Point, ItemPointBinding>(R.layout.item_point) /*{
        onCreate { println("Created ${binding.item} at position $position") }
        onBind { println("Bound ${binding.item} at position $position") }
        onClick { context.toast("Click on ${binding.item} at position $position") }
        onLongClick { context.toast("Long click on ${binding.item} at position $position") }
        onRecycle { println("Recycled ${binding.item} at position $position") }
    }*/
    .into(list)
```
API for Java is not so cool, at least right now...

**LayoutHandler / TypeHandler**:
With the listeners being specific for each type, the "LayoutHandler" should become a "TypeHandler" and returns more than just the layout. Probably something like:

```kotlin
val typeHeader = Type<ItemHeaderBinding>(R.layout.item_header)
    .onBind { println("Bound ${binding.item} at position $position") }
    .onClick { context.toast("Click on ${binding.item} at position $position") }
    .onLongClick { context.toast("Long click on ${binding.item} at position $position") }
    .onRecycle { println("Recycled ${binding.item} at position $position") }

val typePoint = Type<ItemPointBinding>(R.layout.item_point)
    .onClick { context.toast("Click on ${binding.item} at position $position") }

val typeHeaderFist = Type<ItemHeaderFirstBinding>(R.layout.item_header_first) 
    .onBind { println("Bound ${binding.item} at position $position") }

LastAdapter.with(Data.items, BR.item) {
    when (item) {
        is Header -> if (position == 0) typeHeaderFirst else typeHeader
        is Point -> typePoint
        else -> null
    }
}.into(list)
```

**Data Binding**:
I'm even considering the possibility of letting the "users" decide if they want to use Data Binding or not, and do the binding manually if they want.

**Feel free to leave your thoughts here :)**

**Comment by stepango** [comment]
Would be great to add stable id's support.

**Comment by nitrico** [comment]
Yes, that seems pretty reasonable. There are a few options to achieve it:

**1)**
```kotlin
LastAdapter.with(Data.items, BR.item)
    .map<Car, ItemCarBinding>(R.layout.item_car)
    .map<Person, ItemPersonBinding>(R.layout.item_person)
    .id {
    	when (item) {
    		is Car -> item.serialNumber
    		is Person -> item.idNumber
    		else -1
    	}
    }
    .into(list)
```

**2)**
```kotlin
LastAdapter.with(Data.items, BR.item)
    .map<Car, ItemCarBinding>(R.layout.item_car, item.serialNumber)
    .map<Person, ItemPersonBinding>(R.layout.item_person, item.idNumber)
    .into(list)
```

**3)**
Try to find out a way to manage it internally. Suggestions?

What makes more sense?

**Comment by Mahtalitet** [comment]
Hello! Sounds cool, I want to try your lib, but I have some questions. What about portion loading? What if need to add/delete footers (or something else) dynamically? Like show progress in the bottom of list while loading items for second page?

**Comment by nitrico** [comment]
Hi @Mahtalitet,

currently, you can't add or remove new types *dynamically* by using the `map` method as the adapter is created after all those calls are executed. But you should have the layouts and item classes ready so you can add all the types that you think could be added to the list (those headers and footers), even if they finally don't.

If you use an `ObservableList` you can add or remove items of any kind at any moment so you can have an item type representing the "Loading more" status and add it when you reach the end of the list (I think you will need `recyclerView.addOnScrollListener`). Then, when the loading is done, remove that item and add the loaded new items to the list.

**Comment by nitrico** [comment]
@stepango the easiest way I found to support stable ids is to make item classes implement an interface and then overriding a method that returns its id. Is it ok? 

```java
// Java
public class Car implements StableId {
    private Long serialNumber;
    private String model;

    public Car(Long serialNumber, String model) {
        this.serialNumber = serialNumber;
        this.model = model;
    }

    public Long getSerialNumber() {
        return serialNumber;
    }

    public String getModel() {
        return model;
    }

    @Override
    public long getStableId() {
        return serialNumber;
    }
}
```
```kotlin
// Kotlin
class Person(val id: Long, val name: String, val surname: String) : StableId {
    override val stableId = id
}
```

**Comment by stepango** [comment]
@nitrico for now im using
```
override fun getItemId(position: Int): Long {
    return list[position].hashCode().toLong()
}
```
Not ideal and works only for data classes(or custom hashCode() implementation). 
I like the 4th option, but not every object could have id as long, in this case, we'll get additional allocations.
5th option exactly what I'm thinking about, it seems to be cleanest and efficient way of getting object id. 

@nitrico how do you feel about enabling stable Id's by default?

**Comment by stepango** [comment]
Regarding other changes. I'm not sure how other developers use this library, but removing custom `onClick` and `onLongClick` listeners sounds reasonable for me, `onBind` should be enough to set listeners, if it's not in xml already.

**Comment by nitrico** [comment]
I think I'm going to use this `StableId` interface, but not sure about enabling it by default. Anyway, it will only add a `true` to the constructor: `LastAdapter.with(items, BR.item, true)...`
