### ISSUE TITLE
Is it possibile to have the same layout for different screen orientation?

### ISSUE THREAD

**Issue by eloquentbit** [nitrico/LastAdapter#11]
Hi, thanks for this excellent library; I would know if it possible to have two different layouts for a recyclerview item (one for portrait mode and one for landscape) handled with the same item model.
Thanks

**Comment by nitrico** [comment]
Hi @eloquentbit,

Yes, it is possible. The simplest way (if you don't need listeners/callbacks) is to do it in the traditional way: having a layout in `res\layout` and another with the same name in `res\layout-land` folder.

**Comment by eloquentbit** [comment]
@nitrico Thank you. What if I need also listeners/callback? BTW I'll try asap.

**Comment by nitrico** [comment]
Did it work?

If you need to use the callbacks, the binding class for each item is needed and given that you have different layouts (even with the same name) the binding class would be different for each layout. So, here, I would recommend you to use different layout names (so you can easily see the two different binding classes) and check for orientation in the getItemType method of the TypeHandler interface. You will have one item model but two "item types".
