### ISSUE TITLE
SortedList support

### ISSUE THREAD

**Issue by stepango** [nitrico/LastAdapter#13]
Just find out a nice talk about RecyclerView optimisations

https://realm.io/news/360andev-yigit-boyar-pro-recyclerview-android-ui-java/?utm_source=Android+Weekly&utm_campaign=a73cc3ac35-Android_Weekly_232&utm_medium=email&utm_term=0_4eb677ad19-a73cc3ac35-337949305

And this question on stackowerflow:http://stackoverflow.com/questions/29795299/what-is-the-sortedlistt-working-with-recyclerview-adapter

Would be nice to have SortedList support in your lib @nitrico

**Comment by nitrico** [comment]
Hi @stepango,

I watched that talk too and, without actually having used it, I understand that the DiffUtil methods are a simpler generalisation of the same idea. And you should be able to use it with LastAdapter right now:
```kotlin
val adapter = LastAdapter...
val diffResult = DiffUtil.calculateDiff(...)
diffResult.dispatchUpdatesTo(adapter)
```
The thing that (I think) cannot be done is what he says later about rebinding only certain views in a viewholder using a payload.

Not sure, but I don't think that using these methods is more efficient than using an ObservableList. Unless I'm missing something... if you just want to keep your items in order, what I would do is to insert them in order in an ObservableList.
