### ISSUE TITLE
Support auto-loading paginated data

### ISSUE THREAD

**Issue by Nutomic** [nitrico/LastAdapter#14]
We have many REST endpoints that return paginated data. This means we get eg 30 items from an API call, and need to load additional items from the server as the user scrolls. As far as I can see, this is not supported in LastAdapter.

I might be able to contribute this functionality. Do you think this makes sense in LastAdapter? And what should the API look like? 

These are the necessary parameters for pagination:
- page loader callback (takes page number, returns list of new items)
- number of items remaining to auto-load (eg if this is set to 10, load when less than 10 items are remainig before the end of the list)
- first page number (optional, can be 0 by default)
- item count (optional, can be `Integer.MAX_VALUE` by default)

**Comment by brh** [comment]
@Nutomic I am not 100% sure, but isn't the standard way of handling this is say you have 31 items and 30 would be a spinner or loading animation.  Then when the data is available notifyDataSetChanged, depending on how you pass your list to LastAdapter.

I am just looking into which library to use and this is on my list, just now sure why it doesn't have a bigger following...

**Comment by nitrico** [comment]
@Nutomic, I agree with @brh that it is something that could be easily implemented on top of any adapter, so I don't see the need to include it in the library. 

But, please, feel free to reopen the discussion if see read advantages on including it.
