### ISSUE TITLE
override getItemId

### ISSUE THREAD

**Issue by yshinkarev** [nitrico/LastAdapter#27]
How I can did it?

**Comment by nitrico** [comment]
If you want to use stable ids, then all the classes you use the adapter needs to implement `StableId `. 

For example, if you only use `User`s in your adapter

```java
new LastAdapter(users, BR.item, true) // <- 'true' enables stable ids
    .map(User.class, R.layout.item_user)
    .into(recyclerView)
```
then `User` must implement `StableId`:
```java
public class User implements StableId {

    private long userId;

    //...

    @Override public long getStableId() {
        return userId; // <- return a long that is unique for this user
    }
}
```

**Comment by yshinkarev** [comment]
nitrico, undestood. But, frankly, seems some complex.
I have entity and should implements non-data layer interface...

**Comment by nitrico** [comment]
Yes, I understand but haven't found a better approach :/

Please, feel free to comment or open a PR if you find a better way to achieve it.
