### ISSUE TITLE
Change layout by condition

### ISSUE THREAD

**Issue by danielpassos** [nitrico/LastAdapter#29]
Is possible to I access my layout to change the text color like

```java
if(item.price > 100) {
// change my TextViewColor
}
```

instead of use LayoutHandler with 2 differents layout:

```
LastAdapter(items, BR.something)
                .layout { item, position ->
                    if (items[position].price > 100) {
                        R.layout.item_red
                    } else {
                        R.layout.item_green
                    }
                }.into(something)
```

**Comment by danielpassos** [comment]
I just realized I can do it on `Type` using `onCreate/onRecycle`.

Nevermind

**Comment by nitrico** [comment]
Hey, wait a second! :) Yes, it is possible, in a few different ways. I would recommend you this one:

```xml
<TextView
    ...
    android:textColor="@{item.price > 100 ? @color/red : @color/green}"/>
```

**Comment by danielpassos** [comment]
Hey @nitrico Thanks for the tip, 

It's not so simple, price was only an example, anyway... `Type` works for me and I have only one type and only one layout ;)
