### ISSUE TITLE
Diff Utils usage

### ISSUE THREAD

**Issue by gaara87** [nitrico/LastAdapter#30]
It would be really amazing if [DiffUtils](https://developer.android.com/reference/android/support/v7/util/DiffUtil.html) can be plugged in with this library. Are you planning on doing it?

**Comment by nitrico** [comment]
I would say that it is possible to use it right now. What is your suggestion?

**Comment by nitrico** [comment]
Please, feel free to reopen the issue if you come up with any suggestion.
