### ISSUE TITLE
Error:Execution failed for task ':app:kaptDebugKotlin'. > Compilation error. See log for more details

### ISSUE THREAD

**Issue by santafebound** [nitrico/LastAdapter#31]
I've set the up project as specified in the README but get the following error:

Error:Execution failed for task ':app:kaptDebugKotlin'.
> Compilation error. See log for more details

**Comment by nitrico** [comment]
Try a Build/Clean Project, Build/Rebuild Project.

If the problem is still present, it is most likely due to a mistake in the layout file. You can have more info in the "Gradle Console" panel in Android Studio.

**Comment by nitrico** [comment]
Please, feel free to reopen the issue if are still experiencing any problem.
