### ISSUE TITLE
Mixing version can lead to runtime crashes

### ISSUE THREAD

**Issue by VJYMAK** [nitrico/LastAdapter#33]
`apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.fintech.assetvantage"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dataBinding{
        enabled true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    kapt 'com.android.databinding:compiler:3.0.0-beta6'
    implementation 'com.github.nitrico.lastadapter:lastadapter:2.2.2'
}
`
My app:build.gradle file is like above.
support library  dependacy gives error like **Mixing version can lead to runtime crashes**

**Comment by nitrico** [comment]
LastAdapter needs RecyclerView support library. Internally it is using a previous version, that's why you are mixing different versions of the support library. Try adding:
`'implementation 'com.android.recyclerview-v7:26.1.0'`

**Comment by nitrico** [comment]
Does it solve your problem?

**Comment by VJYMAK** [comment]
Thanks. It worked.

**Comment by am9072** [comment]
For those who still getting some error is because of android-support conflicting versions
Solution :
[https://youtu.be/UDLqFbat7n0](url)

This will solve your problem.
