### ISSUE TITLE
Changelog for version 2.3.0?

### ISSUE THREAD

**Issue by kirtan403** [nitrico/LastAdapter#35]
I see new version 2.3.0 but no change log there. We use LastAdapter in every project. It is important to know the changes before updating. Can you please provide the changes? 

Thanks a lot for the wonderful library!

**Comment by nitrico** [comment]
Changelog updated: https://github.com/nitrico/LastAdapter/blob/master/CHANGELOG.md

Thanks @kirtan403 :)

**Comment by kirtan403** [comment]
Thank you for the changelog! That IndexOutOfBound exception was a pain in the neck! Thanks for fixing it.

@nitrico A one more request, can you provide an example of a thing I found on your changelog for version 2.2.0, 
> New: Added support for different variable names depending on the type, while still support the old "only one variable name"-style for all types.

I mean, you are talking about, `BR.item` (if I am not wrong). I am unable to find any examples of it in your documentation.

**Comment by nitrico** [comment]
I've never showed it too much because it is kind of an experimental feature that I have barely tested but you can use it like this.

```kotlin
LastAdapter(list)
    .map<Car>(R.layout.item_car, BR.car)
    .map<Person>(R.layout.item_person, BR.person)
    .into(recyclerView)
```

Also, when you create a type:
`val carType = Type<ItemCarBinding>(R.layout.item_car, BR.car)`

Please, let me know if it works fine for you :)
