### ISSUE TITLE
How to Redraw/notifyDatachange when after property value change

### ISSUE THREAD

**Issue by danielpassos** [nitrico/LastAdapter#37]
Hi,

I have an `ObservableArrayList` of a simple Pojo `Message`

```java
private final ObservableArrayList<Message> messageList = new ObservableArrayList<>();

new LastAdapter(messageList, BR.message)
                .map(Message.class, R.layout.item_message)
                .into(mRecycleView);
```

When the user clicks on an `ImageView` I wanna mark it as read and redraw this _line/item_. I have added an event handler for this.

```xml
<import type="..Handler" />

<variable
    name="message"
    type="....model.Message" />

<ImageView
    android:id="@+id/read"
    android:onClick="@{(view) -> Handler.markAsread(view, message)}"
    android:visibility="@{notificacao.lido ? View.GONE : View.VISIBLE}"
    ...
 />
```

```java
public static class Handler {
    public static void markAsread(View view, Message message) {
        message.setRead(true);
    }
}
```

But I have no idea how to redraw this item on the RecyclerView. Just change the `Message` attribute seems does not work.

**Comment by danielpassos** [comment]
I know I can do `view.setVisibility(View.GONE);` on `markAsread` but it's only a example code ;)

**Comment by nitrico** [comment]
To redraw an item when you click on it, you can use `adapter.notifyItemChanged(position)`
