### ISSUE TITLE
Error on BR

### ISSUE THREAD

**Issue by icarusud** [nitrico/LastAdapter#4]
Hi, I'm trying to use LastAdapter, and have a problem. I refered app on github, and have error "Unresolved reference: BR". Is this error occur before?

Here's my item layout source

    <layout xmlns:android="http://schemas.android.com/apk/res/android" >

    <data>
        <variable name="item" type="com.example.icarusud.project.RecyclerViewItem" />
    </data>

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="@{item.text}" />
    </layout>

**Comment by nitrico** [comment]
Hi @icarusud,

BR is a class generated by the Data Binding library. It often needs a clean/rebuild/make in Android Studio to be generated for your project.

Other things you might want to check:
- Your layout file seems to be right. Just check again the package for the RecyclerViewItem
- Gradle plugin version is 1.5 or higher
- Data Binding is enabled in your module build.gradle:
```xml
android {
    ...
    dataBinding { 
        enabled true 
    }
}
```

**Comment by nitrico** [comment]
Hi @icarusud, please let me know if you got it working.

**Comment by icarusud** [comment]
@nitrico Sorry, but it does'nt work.

Here is my build.gradle


    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply plugin: 'kotlin-android-extensions'
    android {
        compileSdkVersion 24
        buildToolsVersion "24.0.0"

    defaultConfig {
        applicationId "com.example.icarusud.recyclerviewtest"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
        dataBinding {
            enabled true
        }
        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }
    }
    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.12'
        compile 'com.android.support:appcompat-v7:24.1.1'
        compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    //recyclerview
    compile "com.android.support:recyclerview-v7:24.1.1"

    //lastadapter
    compile 'com.github.nitrico.lastadapter:lastadapter:1.1.1'
    }
    repositories {
        mavenCentral()
    }

And My  MainActivity

    class MainActivity : AppCompatActivity() {
    val arrlist = ObservableArrayList<Any>()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        arrlist.add("A")
        arrlist.add("B")
        arrlist.add("C")
        arrlist.add("D")
        arrlist.add("E")
        LastAdapter.with(arrlist,BR.item).map(ListItem::class.java,R.layout.item_list).into(recyclerview)
        }
    }

Is there anything wrong with my code?

**Comment by nitrico** [comment]
I don't see anything wrong :/

Can you please try using this build.gradle file? I've just added the two lines starting with `kapt`. You might need to change the 2.1.2 version I used for the data binding compiler. You should use the same you're using in `classpath "com.android.tools.build:gradle:YOUR_VERSION"` in your project.

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"

defaultConfig {
    applicationId "com.example.icarusud.recyclerviewtest"
    minSdkVersion 15
    targetSdkVersion 24
    versionCode 1
    versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dataBinding {
        enabled true
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

//recyclerview
compile "com.android.support:recyclerview-v7:24.1.1"

//lastadapter
compile 'com.github.nitrico.lastadapter:lastadapter:1.1.1'

kapt "com.android.databinding:compiler:2.1.2"
}

repositories {
    mavenCentral()
}

kapt { generateStubs = true }
```

**Comment by icarusud** [comment]
@nitrico  It worked! Thanks you for help

**Comment by nitrico** [comment]
Cool :smile:  Thank you for reporting the problem. I think I should add that to the readme file.
