### ISSUE TITLE
How listen item click listener

### ISSUE THREAD

**Issue by AndroFlo** [nitrico/LastAdapter#41]
Hello,

Is it possible to liste for item click listern ?

Thank's

**Comment by nitrico** [comment]
It is possible, take a look at the samples

https://github.com/nitrico/LastAdapter/blob/master/app/src/main/java/com/github/nitrico/lastadapter_sample/ui/JavaListFragment.java

and 

https://github.com/nitrico/LastAdapter/blob/master/app/src/main/java/com/github/nitrico/lastadapter_sample/ui/KotlinListFragment.kt

**Comment by AndroFlo** [comment]
Thank you and sorry for the question
