### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by ptrbrynt** [nitrico/LastAdapter#45]
Just tried to update my project to AndroidX (https://developer.android.com/topic/libraries/support-library/androidx-rn) and LastAdapter took issue with the change, despite the Refactoring Tool claiming to use dependency translation to enable compatibility with Support-library-based libraries.

**Comment by nekdenis** [comment]
Just publish it please 
https://github.com/nitrico/LastAdapter/pull/48

**Comment by Frozenstep** [comment]
@nitrico Is it possible for this to be fixed? There's an open pull request that seems like it could fix the issue

**Comment by andrewclaus** [comment]
This library seems to be the last issue when attempting to migrate my project to AndroidX. Has anyone found a workaround or alternate library to get this working?

**Comment by andrewclaus** [comment]
@ptrbrynt why close? how did you resolve this issue? Thanks!
