### ISSUE TITLE
Use DiffUtil to update list content

### ISSUE THREAD

**Issue by markusressel** [nitrico/LastAdapter#47]
Hey there, really awesome little library 👍 

The RecyclerView support library includes a tool to calculate the difference between two lists and update the adapter's content with more precision. It's called [DiffUtil](https://android.jlelse.eu/smart-way-to-update-recyclerview-using-diffutil-345941a160e0).

Dou you think it would be feasible to include this functionality in this library by providing a seperate method next to ```notifyDataSetChanged()``` and all the others, that uses this utility?

~~I am willing to invest some time into implementing this if you are interested.~~

Sorry I just saw this was already asked a while ago in #30.
I think this is basic stuff that should be included in every RecyclerView adapter. I guess I could just implement it in my own code, but getting it for free through this library would be even better.

**Comment by m3ntos** [comment]
LastAdapter already supports ObservableList, so I guess something like this [DiffObservableList](https://github.com/evant/binding-collection-adapter/blob/master/bindingcollectionadapter-recyclerview/src/main/java/me/tatarka/bindingcollectionadapter2/collections/DiffObservableList.java)  might be helpful. I think you can just use it as it is right now. Or try to include it into this library, to avoid some boilerplate code, if you think it's worth it.

I also think it would be nice to have DiffUtil out of the box. It's really useful.

**Comment by markusressel** [comment]
I am using epoxy now, which is maintained much faster.
