### ISSUE TITLE
payload binding

### ISSUE THREAD

**Issue by FunnyDevs** [nitrico/LastAdapter#7]
Is possibile to handle the update of only some item attributes and not entire item???

**Comment by nitrico** [comment]
Hi @FunnyDevs,

I don't think it could be done at the library level. At least it would be pretty hard and, in my opinion, not so useful. Can you show me a good use case for this situation?

What you could do is to add another version of your model classes with only the fields you want to keep updated and put those classes' objects in the ObservableList, instead of the original ones.

**Comment by FunnyDevs** [comment]
I show you my situation: i have a list with some content and user thumbnail; if i change my user picture, i would like to change only the user thumbnail without rebind entire model.

**Comment by nitrico** [comment]
Is it because of some transitions or something like that? I don't think it is a big deal to rebind the entire object.

**Comment by FunnyDevs** [comment]
Some elements of the list have a video content with autoplay and so, rebinding entire object, the videos lose their state

**Comment by nitrico** [comment]
Ok, it looks like a good reason. But, as I said, it won't be easy to include in the library, if even possible.

However, I think you can achieve what you want by not using data binding for this particular view in your layout. Instead, use the .onBindListener method of LastAdapter to manually update its value when you consider it should be done.

**Comment by FunnyDevs** [comment]
mmm ok, but how i can do this? only removing "<layout"> from the xml and handle from bindlistener?

**Comment by nitrico** [comment]
No, you need that `<layout>` tag.

Let's say your VideoItem class has two fields: String videoTitle and String videoUrl. Then, you have to do something like this:

```xml
<layout>

	<data>
		<variable name="item" type="...VideoItem" />
	</data>

	<LinearLayout ...>

		<!-- You are using Data Binding for this TextView -->
		<TextView ... 
			android:text="@{item.videoTitle}" />

		<!-- you DO NOT use Data Binding (the '@{...}' thing) here -->
		<YourVideoView ... 
			android:id="@+id/videoView" />

	</LinearLayout>

</layout>
```

```java
LastAdapter.with(yourListOfItems, BR.item)
		.map(VideoItem.class, R.layout.item_video)
                .onBindListener(new LastAdapter.OnBindListener() {
                    @Override
                    public void onBind(@NotNull Object item, @NotNull View view, int type, int position) {
                    	if (item instanceof VideoItem && type == R.layout.item_video) {
                    		VideoItem videoItem = (VideoItem) item;
                    		ItemVideoBinding itemVideoBinding = DataBindingUtil.getBinding(view);

                    		// the title is already bound
                    		// you manually bind the videoView the way you want:
                    		itemVideoBinding.videoView.setVideoUrl(videoItem.videoUrl); // ??
                    	}                 		
                    }
                })
                .into(list);
```

**Comment by FunnyDevs** [comment]
ok, it all makes perfect sense to me now. Thank you!

**Comment by nitrico** [comment]
You are welcome :)
