### ISSUE TITLE
How can one set OnChildClickListener for item

### ISSUE THREAD

**Issue by syedalinaqi** [nitrico/LastAdapter#8]
is it possible to add image in `imageview` via picasso

```
<ImageView
android:layout_width="match_parent"
android:layout_height="match_parent"
android:src="@{viewmodel.firstImage}"
android:id="@+id/imageView3" />
```

**Comment by nitrico** [comment]
Yes, you have to create a custom setter annotated with `@BindingAdapter`. 

There is more information and an example with Picasso here: https://developer.android.com/topic/libraries/data-binding/index.html#custom_setters

**Comment by syedalinaqi** [comment]
Thanks.. Also can you teel me that how can one `setOnChildClickListener` for item using LastAdapter?

**Comment by nitrico** [comment]
I understand that what you're trying to do is to set a click listener for specific views inside an item, is it right?

You can set it in the layout `android:onClick="@{v -> item.onItemClick(v)}"` and then implement that `onItemClick(View view)` method on the item type class.

**Comment by syedalinaqi** [comment]
@nitrico Thanks but it is not working for me. I did

```
public void onShareClickListener(Item i,View view)
    {
        Toast.makeText(view.getContext(),"Share Clickedon:"+i.propertyText,Toast.LENGTH_SHORT).show();
    }
```
and in layout 

` android:onClick="@{(theView) -> listeners.onShareClickListener(item,theView)}"`

**Comment by nitrico** [comment]
I think you mixed the two alternatives showed on the link. 

There is one with the method implemented in the Item class (https://github.com/nitrico/LastAdapter/issues/6#issuecomment-252056255) and another that implement the method statically in another class called Listener (https://github.com/nitrico/LastAdapter/issues/6#issuecomment-252266788).

If you are using the second one, make sure you import that Listeners class as it is done in the example.

**Comment by syedalinaqi** [comment]
I did ths

```
<variable
            name="listeners"
            type="com.example.misc.Listeners" />
```

**Comment by nitrico** [comment]
Do this instead
```xml
<data>
    <variable name="item" type="com.example.misc.Item" />
    <import type="com.example.misc.Listeners" />
</data>
```
and then use Listeners with capital 'L'. 
```xml
android:onClick="@{(theView) -> Listeners.onShareClickListener(item,theView)}"
```
Also, add the `static` keyword to the `onShareClickListener` method inside `Listeners`.

**Comment by syedalinaqi** [comment]
@nitrico thanks man.. You have been a great help... i was missing the `static` word in the method name..
Thanks.. and can you tell me if there is a way to add **Load More Functionality** to the `RecyclerView` keeping in check the LastAdapter

**Comment by nitrico** [comment]
I don't think you can use that library and LastAdapter at the same time, but you can try.

Adding "load more" functionality shouldn't be very complex, though. If you are using an ObservableList to keep your items, you only need to add more items to that list at the moment you reach the end of the list. You can use `recyclerView.addOnScrollListener` method to do it: http://stackoverflow.com/a/26643292

**Comment by syedalinaqi** [comment]
Thanks.. Will do it..

**Comment by nitrico** [comment]
You're welcome :)

I would also like to find a way to use those features while using LastAdapter, but didn't test them yet. So please let me know if you find something that works.

**Comment by syedalinaqi** [comment]
Ok... tell me where and I will let u know If i find something..

**Comment by nitrico** [comment]
Right here, for example, or by email nitrico@gmail.com  Thanks!

**Comment by syedalinaqi** [comment]
k.
