### ISSUE TITLE
Doesn't work with RecyclerView support lib version 25.0.0

### ISSUE THREAD

**Issue by nitrico** [nitrico/LastAdapter#9]
The library doesn't work properly when I try to update the recyclerview-v7 dependency to version 25.0.0.

Some items are not bound correctly or not bound at all. I don't know if it is related to a modification introduced on purpose to the RecyclerView library or a bug.

Any help would be appreciated.

**Comment by stepango** [comment]
I noticed some problems too.

**Comment by nitrico** [comment]
Should be fixed in version 1.2.4
